### PR TITLE
re-frame / Reagent

### PR DESCRIPTION
**Pull request by jbest84**
Naive approach for [re-frame](https://github.com/Day8/re-frame) / [reagent](http://reagent-project.github.io/). Other Clojurescript/Reagent devs feel free to tear this apart, I am very new to cljs. Demo available [here](http://jbest84.github.io/js-repaint-perfs/re-frame/index.html).

### CODE REVIEW

**Comment by mathieuancelin** [comment]
Hi, 

can you update your PR so I can merge it ? thanks

**Comment by jbest84** [comment]
Done

**Comment by mathieuancelin** [comment]
Thanks :-)

**Comment by jbest84** [comment]
Thanks for the merge!

**Pull request merged**
